-- MySQL Script generated by MySQL Workbench
-- Fri May 24 23:17:50 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema fitness
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fitness
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fitness` DEFAULT CHARACTER SET utf8 ;
USE `fitness` ;

-- -----------------------------------------------------
-- Table `fitness`.`subscriptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitness`.`subscriptions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `start_date` DATE NOT NULL,
  `due_date` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitness`.`locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitness`.`locations` (
  `id` INT NOT NULL,
  `address` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitness`.`pictures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitness`.`pictures` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `size` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitness`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitness`.`customers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `subscriptions_id` INT NOT NULL,
  `locations_id` INT NOT NULL,
  `pictures_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_customers_subscriptions_idx` (`subscriptions_id` ASC) VISIBLE,
  INDEX `fk_customers_locations1_idx` (`locations_id` ASC) VISIBLE,
  INDEX `fk_customers_pictures1_idx` (`pictures_id` ASC) VISIBLE,
  CONSTRAINT `fk_customers_subscriptions`
    FOREIGN KEY (`subscriptions_id`)
    REFERENCES `fitness`.`subscriptions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customers_locations1`
    FOREIGN KEY (`locations_id`)
    REFERENCES `fitness`.`locations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customers_pictures1`
    FOREIGN KEY (`pictures_id`)
    REFERENCES `fitness`.`pictures` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitness`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitness`.`employees` (
  `id` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  `salary` DOUBLE NULL,
  `locations_id` INT NOT NULL,
  `pictures_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_employees_locations1_idx` (`locations_id` ASC) VISIBLE,
  INDEX `fk_employees_pictures1_idx` (`pictures_id` ASC) VISIBLE,
  CONSTRAINT `fk_employees_locations1`
    FOREIGN KEY (`locations_id`)
    REFERENCES `fitness`.`locations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employees_pictures1`
    FOREIGN KEY (`pictures_id`)
    REFERENCES `fitness`.`pictures` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitness`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitness`.`products` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `amount` INT NOT NULL,
  `barcode` INT NOT NULL,
  `price` DOUBLE NOT NULL,
  `due_date` DATE NOT NULL,
  `locations_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_products_locations1_idx` (`locations_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_locations1`
    FOREIGN KEY (`locations_id`)
    REFERENCES `fitness`.`locations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitness`.`equipment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitness`.`equipment` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `amount` INT NOT NULL,
  `cost` DOUBLE NOT NULL,
  `locations_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_equipment_locations1_idx` (`locations_id` ASC) VISIBLE,
  CONSTRAINT `fk_equipment_locations1`
    FOREIGN KEY (`locations_id`)
    REFERENCES `fitness`.`locations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitness`.`customer_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitness`.`customer_log` (
  `log_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `action` VARCHAR(45) NOT NULL,
  `old_first_name` VARCHAR(45) NULL,
  `new_first_name` VARCHAR(45) NULL,
  `old_last_name` VARCHAR(45) NULL,
  `new_last_name` VARCHAR(45) NULL,
  `timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`log_id`))
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
